#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# install homebrew
# or not
# install zsh, dotzsh, jq, curl, fzf, reflex, git, neovim, tmux, docker, firefox, fonts, browsh, asdf
sudo ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime
sudo rm -f /etc/dpkg/dpkg.cfg.d/excludes
sudo apt-get update
xargs -r sudo apt-get install -y --no-install-recommends <${BASEDIR}/packages/apt
xargs -rI{} curl -s {} <${BASEDIR}/packages/github | bash

[[ -f "${BASEDIR}/gitconfig" ]] && ln -sf ${BASEDIR}/gitconfig ${HOME}/.gitconfig.template
[[ -f "${BASEDIR}/gitmessage" ]] && ln -sf ${BASEDIR}/gitmessage ${HOME}/.gitmessage.template
[[ -d "${BASEDIR}/git-templates" ]] && ln -sf ${BASEDIR}/git-templates ${HOME}/.git-templates
[[ -d "${HOME}/.asdf" ]] || git clone --depth 1 --branch v0.8.0 https://github.com/asdf-vm/asdf.git ${HOME}/.asdf
# TODO: create $HOME/.default-python-packages
# TODO: create $HOME/.default-golang-pkgs

[[ -d "${HOME}/.oh-my-zsh" ]] || git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh.git ${HOME}/.oh-my-zsh
[[ -d "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k" ]] || git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${HOME}/.oh-my-zsh/custom/themes/powerlevel10k

[[ -f "${BASEDIR}/p10k.zsh" ]] && ln -sf ${BASEDIR}/p10k.zsh ${HOME}/.p10k.zsh
[[ -f "${BASEDIR}/zshrc" ]] && ln -sf ${BASEDIR}/zshrc ${HOME}/.zshrc
[[ -f "${BASEDIR}/aliases" ]] && ln -sf ${BASEDIR}/aliases ${HOME}/.aliases
[[ -f "${BASEDIR}/tmux.conf" ]] && ln -sf ${BASEDIR}/tmux.conf ${HOME}/.tmux.conf
[[ -f "${BASEDIR}/vimrc" ]] && ln -sf ${BASEDIR}/vimrc ${HOME}/.vimrc
mkdir -p ${HOME}/.config/nvim
[[ -f "${BASEDIR}/vimrc" ]] && ln -sf ${BASEDIR}/vimrc ${HOME}/.config/nvim/init.vim
[[ -f "${HOME}/.zshrc" ]] || cp -f ${HOME}/.oh-my-zsh/templates/zshrc.zsh-template ${HOME}/.zshrc

tmux new-session -d -s setup-tmux 'nvim +"TmuxlineSnapshot $HOME/.vim/plugged/tmuxline.vim/tmux.conf" +qa'

sudo chsh -s $(which zsh) $(whoami)
$(which zsh) --login